name: hotspot-voucher-automator
services:
  hotspot-voucher:
    image: hotspot-voucher:latest
    container_name: hotspot-voucher
    restart: unless-stopped
    ports:
      - target: 3001
        published: "3001"
        protocol: tcp
    environment:
      NODE_ENV: production
      PORT: "3001"
      TZ: Asia/Jakarta
    volumes:
      - type: bind
        source: /DATA/AppData/hotspot-voucher/logs
        target: /app/logs
      - type: bind
        source: /DATA/AppData/hotspot-voucher/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/hotspot-voucher/config
        target: /app/config
    networks:
      - hotspot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      casaos.name: "HotSpot Voucher"
      casaos.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mikrotik.png"
      casaos.description: "Automated HotSpot Voucher System v2.0.1"
      casaos.main_port: "3001"
      casaos.category: "Network"
      casaos.developer: "Nichiemaru"
      casaos.project_url: "https://github.com/nichiemaru/hotspot-voucher-automator"

networks:
  hotspot-network:
    driver: bridge
    name: hotspot-network

x-casaos:
  architectures:
    - amd64
    - arm64
  main: hotspot-voucher
  description:
    en_us: "Automated HotSpot Voucher System with MikroTik integration, payment gateway, and WhatsApp notifications. Perfect for internet cafes and hotspot providers."
  tagline:
    en_us: "Complete voucher automation solution"
  developer: "Nichiemaru"
  author: "Nichiemaru"
  icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mikrotik.png"
  screenshot_link:
    - "https://raw.githubusercontent.com/nichiemaru/hotspot-voucher-automator/main/screenshots/dashboard.png"
    - "https://raw.githubusercontent.com/nichiemaru/hotspot-voucher-automator/main/screenshots/admin.png"
  thumbnail: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mikrotik.png"
  title:
    en_us: "HotSpot Voucher Automator"
  category: "Network"
  project_url: "https://github.com/nichiemaru/hotspot-voucher-automator"
  port_map: "3001"
