version: '3.8'

services:
  hotspot-voucher-v2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hotspot-voucher-v2
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=Asia/Jakarta
    volumes:
      - /DATA/AppData/hotspot-voucher-v2/logs:/app/logs
      - /DATA/AppData/hotspot-voucher-v2/data:/app/data
      - /DATA/AppData/hotspot-voucher-v2/config:/app/config
    networks:
      - hotspot-network-v2
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "casaos.name=HotSpot Voucher v2"
      - "casaos.icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mikrotik.png"
      - "casaos.description=Automated HotSpot Voucher System v2.0.1"
      - "casaos.main_port=3001"
      - "casaos.category=Network"
      - "casaos.developer=Nichiemaru"
      - "casaos.version=2.0.1"

  hotspot-db:
    image: postgres:15-alpine
    container_name: hotspot-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=hotspot_voucher
      - POSTGRES_USER=hotspot_user
      - POSTGRES_PASSWORD=hotspot_pass_2024
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - /DATA/AppData/hotspot-voucher/postgres:/var/lib/postgresql/data
    networks:
      - hotspot-network-v2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotspot_user -d hotspot_voucher"]
      interval: 10s
      timeout: 5s
      retries: 5

  hotspot-fresh:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hotspot-fresh
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=Asia/Jakarta
    volumes:
      - /DATA/AppData/hotspot-fresh/logs:/app/logs
      - /DATA/AppData/hotspot-fresh/data:/app/data
      - /DATA/AppData/hotspot-fresh/config:/app/config
    networks:
      - hotspot-fresh-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "casaos.name=HotSpot Voucher Fresh"
      - "casaos.icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mikrotik.png"
      - "casaos.description=Fresh Install HotSpot Voucher System v2.1.0"
      - "casaos.main_port=3001"
      - "casaos.category=Network"
      - "casaos.developer=Nichiemaru"
      - "casaos.version=2.1.0"
      - "casaos.install_type=fresh"

networks:
  hotspot-network-v2:
    driver: bridge
    name: hotspot-network-v2

  hotspot-fresh-network:
    driver: bridge
    name: hotspot-fresh-network
